services:
  redmine:
    image: tangramor/redmine:6.0.4
    container_name: redmine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './config:/var/www/html/redmine/config'
      - '/home/redmine/public/system/rich:/var/www/html/redmine/public/system/rich'
      - '/home/redmine/plugins:/var/www/html/redmine/plugins'
      - '/home/redmine/files:/var/www/html/redmine/files'
      - '/home/redmine/log:/opt/nginx/logs'
      - '/home/redmine/log:/var/www/html/redmine/log'
      - '/etc/localtime:/etc/localtime'
    networks:
      - redmine
    environment:
      MYSQL_ROOT_PASSWORD: 'Password1'
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/redmine/config/init_db.lock"]

  mysql:
    image: 'mysql:8'
    container_name: redmine_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'Password1'
    volumes:
      - './initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro'
      - '/home/mysql8_data:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime'
    networks:
      - redmine
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

networks:
  redmine:
    driver: bridge
