development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #secret_token:  <%= ENV["SECRET_TOKEN"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #secret_token:  <%= ENV["SECRET_TOKEN"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #secret_token:  <%= ENV["SECRET_TOKEN"] %>